package HopSpot::Model::PgDB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'HopSpot::Schema::PgDB',
    
    connect_info => {
        dsn => 'dbi:Pg:dbname=hopspot',
        user => 'catappuser',
        password => 'tcpip123',
        AutoCommit => q{1},
    }
);

=head1 NAME

HopSpot::Model::PgDB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<HopSpot>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<HopSpot::Schema::PgDB>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.65

=head1 AUTHOR

Nishant Sharma

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
